pipeline {
    agent {
        docker {
        image 'jenkins/slave:latest-jdk11'
        }
    }

    stages {
        stage('SCM') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/Develop']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/apgandhamwar/JenkinsPipeline_Advance']]])
            }
        }

        stage('Build') {
            steps {
                sh 'dotnet build "$WORKSPACE/src/EAApp/EAApp.csproj"'
            }
        }

        stage('Publish') {
            steps {
                sh 'dotnet publish "$WORKSPACE/src/EAApp/EAApp.csproj"'
                archiveArtifacts artifacts: 'src/EAApp/bin/Debug/netcoreapp3.1/publish/*'
            }
        }
    }
}
